### ISSUE TITLE
5th Option for "Suspended Grating Floor" crashes the game instantly when its selected.

### ISSUE THREAD

**Issue by CardsAndGamesYT** [TheEnderek0/QoL-Reloaded#4]
https://user-images.githubusercontent.com/74144694/129781552-a444c300-18e7-4c8f-98a2-786446110b6a.mp4

**Comment by TheEnderek0** [comment]
I tested it a couple of seconds ago and it appears it don't crashes for me
just shows error model and you cannot select it

Still this needs to be fixed

**Comment by TheEnderek0** [comment]
Fixed in the next release
